apiVersion: apps/v1
kind: Deployment
metadata:
  name: auth
  namespace: {{ .Values.namespace }}

spec:
  replicas: {{ .Values.auth.replicaCount }}

  selector:
    matchLabels:
      app: auth

  template:
    metadata:
      labels:
        app: auth

    spec:
      containers:
      - name: auth

        image: "{{ .Values.accountId }}.dkr.ecr.{{ .Values.region }}.amazonaws.com/{{ .Values.auth.image }}:{{ .Values.auth.tag }}"

        env:
  - name: MONGO_URI
    valueFrom:
      secretKeyRef:
        name: mongodb-secret
        key: MONGO_URI

        ports:
        - containerPort: {{ .Values.auth.port }}

---
apiVersion: v1
kind: Service
metadata:
  name: auth-service
  namespace: {{ .Values.namespace }}

spec:
  selector:
    app: auth

  ports:
  - port: {{ .Values.auth.port }}
    targetPort: {{ .Values.auth.port }}

  type: ClusterIP
